INHERIT: ./base-mkdocs.yml
nav:
  - "Eremex Avalonia UI Controls Library": 'index.md'
  - "Get Started":
    - "Get Started": 'get-started/index.md'
    - "Get Started with EMX Controls": 'get-started/get-started-with-emx-controls.md'
    - "Use Standard Avalonia UI Templates to Create a New Project with Eremex Controls": 'get-started/create-new-avalonia-project-using-avalonia-templates.md'
    - "Get Started with EMX Controls on ALT Linux": 'get-started/get-started-with-emx-controls-on-alt-linux.md'
  - "Controls":
    - "Controls": 'controls/index.md'
    - "DataGrid":
      - "DataGrid": 'controls/datagrid/index.md'
      - "Data Binding":
        - "Data Binding": 'controls/datagrid/data-binding/index.md'
        - "Unbound Columns": 'controls/datagrid/data-binding/unbound-columns.md'
      - "Columns": 'controls/datagrid/columns.md'
      - "Rows": 'controls/datagrid/rows.md'
      - "Cells": 'controls/datagrid/cells.md'
      - "Bands": 'controls/datagrid/bands.md'
      - "Data Editing":
        - "Data Editing": 'controls/datagrid/data-editing/index.md'
        - "Custom Editors": 'controls/datagrid/data-editing/custom-editors.md'
      - "Sorting": 'controls/datagrid/sorting.md'
      - "Grouping": 'controls/datagrid/grouping.md'
      - "Filter and Search": 'controls/datagrid/filter-and-search.md'
      - "Focus and Navigation": 'controls/datagrid/focus-and-navigation.md'
      - "Row Drag-and-Drop": 'controls/datagrid/row-drag-and-drop.md'
      - "Context Menus": 'controls/datagrid/context-menus.md'
      - "Export": 'controls/datagrid/export.md'
      - "Clipboard": 'controls/datagrid/clipboard.md'
      - "Save and Restore the Layout": 'controls/datagrid/save-and-restore-layout.md'
      - "Styles": 'controls/datagrid/styles.md'
      - "Performance and Data Virtualization": 'controls/datagrid/performance-and-data-virtualization.md'
      - "Examples":
        - "Examples": 'controls/datagrid/examples/index.md'
        - "How to Prevent Opening Popups for Read-only Popup Editors": 'controls/datagrid/examples/how-to-prevent-opening-popups-for-read-only-popup-editors.md'
    - "TreeList and TreeView":
      - "TreeList and TreeView": 'controls/treelist/index.md'
      - "TreeList and TreeView Controls Overview": 'controls/treelist/treelist-and-treeview-overview.md'
      - "Data Binding":
        - "Data Binding": 'controls/treelist/data-binding/index.md'
        - "Binding to Hierarchical Data": 'controls/treelist/data-binding/binding-to-hierarchical-data.md'
        - "Binding to Self-Referential Data Source": 'controls/treelist/data-binding/binding-to-self-referential-data-source.md'
        - "Unbound Mode": 'controls/treelist/data-binding/unbound-mode.md'
        - "Unbound Columns": 'controls/treelist/data-binding/unbound-columns.md'
      - "Columns": 'controls/treelist/columns.md'
      - "Bands": 'controls/treelist/bands.md'
      - "Nodes": 'controls/treelist/nodes.md'
      - "Data Editing":
        - "Data Editing": 'controls/treelist/data-editing/index.md'
        - "Custom Editors in TreeList and TreeView Cells": 'controls/treelist/data-editing/custom-editors.md'
      - "Sorting": 'controls/treelist/sorting.md'
      - "Filter and Search": 'controls/treelist/filter-and-search.md'
      - "Focus and Navigation": 'controls/treelist/focus-and-navigation.md'
      - "Data Validation": 'controls/treelist/data-validation.md'
      - "Node Drag-and-Drop": 'controls/treelist/node-drag-and-drop.md'
      - "Context Menus": 'controls/treelist/context-menus.md'
      - "Export": 'controls/treelist/export.md'
      - "Save and Restore the Layout": 'controls/treelist/save-and-restore-layout.md'
      - "Styles": 'controls/treelist/styles.md'
      - "Performance and Data Virtualization": 'controls/treelist/performance-and-data-virtualization.md'
      - "Examples":
        - "Examples": 'controls/treelist/examples/index.md'
        - "How to Create a TreeView Control and Bind It to a Self Referential Data Source": 'controls/treelist/examples/how-to-create-a-treeview-control-and-bind-it-to-a-self-referential-data-source.md'
        - "How to Create a TreeList Control and Bind It to a Hierarchical Data Source": 'controls/treelist/examples/how-to-create-a-treelist-control-and-bind-it-to-a-hierarchical-data-source.md'
    - "Charts":
      - "Charts": 'controls/charts/index.md'
      - "Get Started with Charts": 'controls/charts/get-started-with-charts.md'
      - "Get Started with Charts - MVVM Pattern": 'controls/charts/get-started-with-charts-mvvm.md'
      - "Cartesian Chart": 'controls/charts/cartesian-chart.md'
      - "Cartersian Series Views":
        - "Cartersian Series Views": 'controls/charts/cartesian-series-views/index.md'
        - "Line Series View": 'controls/charts/cartesian-series-views/line-series-vew.md'
        - "Scatter Line Series View": 'controls/charts/cartesian-series-views/scatter-line-series-view.md'
        - "Point Series View": 'controls/charts/cartesian-series-views/point-series-view.md'
        - "Area Series View": 'controls/charts/cartesian-series-views/area-series-view.md'
        - "Range Area Series View": 'controls/charts/cartesian-series-views/range-area-series-view.md'
        - "Stacked Area Series View": 'controls/charts/cartesian-series-views/stacked-area-series-view.md'
        - "Full-Stacked Area Series View": 'controls/charts/cartesian-series-views/full-stacked-area-series-view.md'
        - "Side-by-side Bar Series View": 'controls/charts/cartesian-series-views/side-by-side-bar-series-view.md'
        - "Side-by-side Range Bar Series View": 'controls/charts/cartesian-series-views/side-by-side-range-bar-series-view.md'
        - "Step Line Series View": 'controls/charts/cartesian-series-views/step-line-series-view.md'
        - "Step Area Series View": 'controls/charts/cartesian-series-views/step-area-series-view.md'
        - "Candlestick Series View": 'controls/charts/cartesian-series-views/candlestick-series-view.md'
        - "Lollipop Series View": 'controls/charts/cartesian-series-views/lollipop-series-view.md'
      - "Crosshair": 'controls/charts/crosshair.md'
      - "Scroll and Zoom in a Chart Control": 'controls/charts/scroll-and-zoom-in-a-chart-control.md'
      - "Heatmap": 'controls/charts/heatmap.md'
    - "Docking UI":
      - "Docking UI": 'controls/docking/index.md'
      - "Get Started with Docking": 'controls/docking/get-started-with-docking.md'
      - "Dock Manager and Dock Items": 'controls/docking/dock-manager.md'
      - "Dock Panes and Containers": 'controls/docking/dock-panes-and-containers.md'
      - "Document Panes": 'controls/docking/document-panes.md'
      - "Document Switcher": 'controls/docking/document-switcher.md'
      - "Perform Dock Operations in Code": 'controls/docking/perform-dock-operations-in-code.md'
      - "Use MVVM Pattern to Populate Dock Items": 'controls/docking/use-mvvm-pattern-to-populate-dock-items.md'
      - "Save and Restore the Layout of Panels": 'controls/docking/save-and-restore-layout.md'
      - "Examples":
        - "Examples": 'controls/docking/examples/index.md'
        - "How to Create a Complex Docking Layout in Code Behind": 'controls/docking/examples/how-to-create-a-complex-docking-layout-in-code-behind.md'
    - "Ribbon":
      - "Ribbon": 'controls/ribbon/index.md'
      - "Ribbon Overview": 'controls/ribbon/ribbon-overview.md'
      - "Pages": 'controls/ribbon/pages.md'
      - "Page Groups": 'controls/ribbon/page-groups.md'
      - "Ribbon Items": 'controls/ribbon/ribbon-items.md'
      - "Galleries": 'controls/ribbon/galleries.md'
      - "Application Button and Main Menu": 'controls/ribbon/application-button-and-main-menu.md'
      - "Quick Access Toolbar": 'controls/ribbon/quick-access-toolbar.md'
      - "Page Header Items": 'controls/ribbon/page-header-items.md'
      - "Key Tips": 'controls/ribbon/key-tips.md'
      - "Ribbon Command Layouts": 'controls/ribbon/ribbon-command-layouts.md'
      - "Ribbon Serialization and Deserialization": 'controls/ribbon/ribbon-serialization-and-deserialization.md'
    - "Toolbars and Menus":
      - "Toolbars and Menus": 'controls/toolbars-and-menus/index.md'
      - "Get Started With Toolbars": 'controls/toolbars-and-menus/get-started-with-toolbars.md'
      - "Toolbars": 'controls/toolbars-and-menus/toolbars.md'
      - "Toolbar Items": 'controls/toolbars-and-menus/toolbar-items.md'
      - "Popup and Context Menus": 'controls/toolbars-and-menus/popup-and-context-menus.md'
      - "Toolbar Serialization and Deserialization": 'controls/toolbars-and-menus/toolbar-serialization-and-deserialization.md'
    - "ListView":
      - "ListView": 'controls/listview/index.md'
      - "Get Started with ListView Control": 'controls/listview/get-started-with-listview.md'
      - "ListView Control Overview": 'controls/listview/listview-overview.md'
    - "PropertyGrid":
      - "PropertyGrid": 'controls/propertygrid/index.md'
      - "PropertyGrid Overview": 'controls/propertygrid/propertygrid-overview.md'
      - "Data Binding and Row Creation": 'controls/propertygrid/data-binding.md'
      - "PropertyGrid Rows": 'controls/propertygrid/rows.md'
      - "Data Search": 'controls/propertygrid/data-search.md'
      - "Data Editing": 'controls/propertygrid/data-editing.md'
      - "Custom Editors": 'controls/propertygrid/custom-editors.md'
      - "Frequently Used API": 'controls/propertygrid/frequently-used-api.md'
    - "Graphics 3D Control":
      - "Graphics 3D Control": 'controls/graphics3dcontrol/index.md'
      - "Get Started with Graphics3DControl": 'controls/graphics3dcontrol/get-started-with-graphics3dcontrol.md'
      - "Graphics3DControl Overview": 'controls/graphics3dcontrol/graphics3dcontrol-overview.md'
      - "Camera": 'controls/graphics3dcontrol/camera.md'
      - "Light": 'controls/graphics3dcontrol/light.md'
      - "Skybox": 'controls/graphics3dcontrol/skybox.md'
      - "Export": 'controls/graphics3dcontrol/export.md'
      - "User Interactions with 3D Models": 'controls/graphics3dcontrol/user-interactions-with-3d-models.md'
      - "System Requirements": 'controls/graphics3dcontrol/system-requirements.md'
    - "Editors":
      - "Editors": 'controls/editors/index.md'
      - "TextEditor": 'controls/editors/texteditor.md'
      - "ButtonEditor": 'controls/editors/buttoneditor.md'
      - "CheckEditor": 'controls/editors/checkeditor.md'
      - "ComboBoxEditor": 'controls/editors/comboboxeditor.md'
      - "DateEditor": 'controls/editors/dateeditor.md'
      - "HyperlinkEditor": 'controls/editors/hyperlinkeditor.md'
      - "MemoEditor": 'controls/editors/memoeditor.md'
      - "PopupColorEditor": 'controls/editors/popupcoloreditor.md'
      - "SegmentedEditor": 'controls/editors/segmentededitor.md'
      - "SpinEditor": 'controls/editors/spineditor.md'
      - "Masks":
        - "Masks": 'controls/editors/masks/index.md'
        - "Numeric Masks": 'controls/editors/masks/numeric-masks.md'
        - "Date-Time Masks": 'controls/editors/masks/date-time-masks.md'
      - "Data Validation": 'controls/editors/data-validation.md'
      - "Custom Editors": 'controls/editors/custom-editors.md'
      - "Examples":
        - "Examples": 'controls/editors/examples/index.md'
        - "How to create a password text box": 'controls/editors/examples/How-to-create-a-password-text-box.md'
    - "Utility Controls":
      - "Utility Controls": 'controls/utility-controls/index.md'
      - "CalendarControl": 'controls/utility-controls/calendarcontrol.md'
      - "GroupBox": 'controls/utility-controls/groupbox.md'
      - "SplitButton": 'controls/utility-controls/splitbutton.md'
      - "SplitContainerControl": 'controls/utility-controls/splitcontainercontrol.md'
      - "TabControl": 'controls/utility-controls/tabcontrol.md'
    - "Windows and Dialogs":
      - "Windows and Dialogs": 'controls/windows-and-dialogs/index.md'
      - "MxWindow": 'controls/windows-and-dialogs/mxwindow.md'
      - "MxMessageBox": 'controls/windows-and-dialogs/messagebox.md'
    - "Application Services":
      - "Application Services": 'controls/app-services/index.md'
      - "IMessageBoxService": 'controls/app-services/messageboxservice.md'
      - "IDialogService": 'controls/app-services/dialogservice.md'
    - "Themes":
      - "Themes": 'controls/themes/index.md'
      - "Register an Eremex Paint Theme": 'controls/themes/register-an-eremex-paint-theme.md'
      - "Modify Control Themes": 'controls/themes/modify-control-themes.md'
    - "Troubleshooting":
      - "Troubleshooting": 'controls/troubleshooting/index.md'
      - "Shadows are not Displayed Correctly for Windows and Menus in OS Astra Linux": 'controls/troubleshooting/shadows-are-not-displayed-correctly-for-windows-and-menus-in-os-astra.md'
  - "What's Included":
    - "What's Included": 'whats-included/index.md'
    - "Assemblies": 'whats-included/assemblies.md'
    - "Project Templates": 'whats-included/project-templates.md'
    - "System Requirements": 'whats-included/system-requirements.md'
    - "Build-time Telemetry": 'whats-included/build-time-telemetry.md'
    - "Technical Support Services": 'whats-included/technical-support-services.md'
    - "MCP Server": 'whats-included/mcp-server.md'
  - "Version History":
    - "Version History": 'version-history/index.md'
    - "Version 1.5": 'version-history/version-1.5.md'
    - "Version 1.4": 'version-history/version-1.4.md'
    - "Version 1.3": 'version-history/version-1.3.md'
    - "Version 1.2": 'version-history/version-1.2.md'
    - "Version 1.1": 'version-history/version-1.1.md'
    - "Version 1.0": 'version-history/version-1.0.md'
  - "Licensing":
    - "Licensing": 'licensing/index.md'
    - "END-USER LICENSE AGREEMENT": 'licensing/eula.md'
  - "API":
    - "Eremex.AvaloniaUI.Controls":
      - "Eremex.AvaloniaUI.Controls": 'API/Eremex.AvaloniaUI.Controls/index.md'
      - "MessageBoxButtons": 'API/Eremex.AvaloniaUI.Controls/MessageBoxButtons.md'
      - "MessageBoxIcon": 'API/Eremex.AvaloniaUI.Controls/MessageBoxIcon.md'
      - "MessageBoxResult": 'API/Eremex.AvaloniaUI.Controls/MessageBoxResult.md'
    - "Eremex.AvaloniaUI.Controls.ApplicationServices":
      - "Eremex.AvaloniaUI.Controls.ApplicationServices": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/index.md'
      - "ApplicationServicesContext": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/ApplicationServicesContext.md'
      - "AvaloniaStorageDialogBase": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/AvaloniaStorageDialogBase.md'
      - "ChoiceDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/ChoiceDialogService.md'
      - "DialogAwareViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogAwareViewModel.md'
      - "DialogButtonType": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogButtonType.md'
      - "DialogButtonViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogButtonViewModel.md'
      - "DialogChoice 1": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogChoice-1.md'
      - "DialogResult": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogResult.md'
      - "DialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogService.md'
      - "DialogWindow": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogWindow.md'
      - "DialogWindowClasses": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DialogWindowClasses.md'
      - "DockType": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/DockType.md'
      - "IActionWindow": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IActionWindow.md'
      - "IChoiceDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IChoiceDialogService.md'
      - "IDialogAwareViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IDialogAwareViewModel.md'
      - "IDialogButtonViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IDialogButtonViewModel.md'
      - "IDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IDialogService.md'
      - "IMessageBoxService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IMessageBoxService.md'
      - "IOpenFileDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IOpenFileDialogService.md'
      - "ISaveFileDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/ISaveFileDialogService.md'
      - "IWindowAwareViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IWindowAwareViewModel.md'
      - "IWindowService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IWindowService.md'
      - "IWindowsManager": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/IWindowsManager.md'
      - "MessageBoxService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/MessageBoxService.md'
      - "OkCancelDialogAwareViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/OkCancelDialogAwareViewModel.md'
      - "OpenFileDialogOptions": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/OpenFileDialogOptions.md'
      - "OpenFileDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/OpenFileDialogService.md'
      - "SaveFileDialogOptions": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/SaveFileDialogOptions.md'
      - "SaveFileDialogService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/SaveFileDialogService.md'
      - "SimpleServiceProvider": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/SimpleServiceProvider.md'
      - "ViewLocatorAttribute": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/ViewLocatorAttribute.md'
      - "WindowAwareViewModel": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/WindowAwareViewModel.md'
      - "WindowManager": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/WindowManager.md'
      - "WindowService": 'API/Eremex.AvaloniaUI.Controls.ApplicationServices/WindowService.md'
