INHERIT: ./base-mkdocs.yml
nav:
  - "Eremex Avalonia UI Controls Library": 'index.md'
  - "快速入门":
    - "快速入门": 'get-started/index.md'
    - "EMX Controls 入门指南": 'get-started/get-started-with-emx-controls.md'
    - "使用标准 Avalonia UI 模板结合 Eremex Controls 创建新项目": 'get-started/create-new-avalonia-project-using-avalonia-templates.md'
    - "在 ALT Linux 上开始使用 EMX Controls": 'get-started/get-started-with-emx-controls-on-alt-linux.md'
  - "控件":
    - "控件": 'controls/index.md'
    - "DataGrid":
      - "DataGrid": 'controls/datagrid/index.md'
      - "数据绑定":
        - "数据绑定": 'controls/datagrid/data-binding/index.md'
        - "未绑定的列": 'controls/datagrid/data-binding/unbound-columns.md'
      - "Columns": 'controls/datagrid/columns.md'
      - "行": 'controls/datagrid/rows.md'
      - "Cells": 'controls/datagrid/cells.md'
      - "Bands": 'controls/datagrid/bands.md'
      - "数据编辑":
        - "数据编辑": 'controls/datagrid/data-editing/index.md'
        - "自定义编辑器": 'controls/datagrid/data-editing/custom-editors.md'
      - "Sorting": 'controls/datagrid/sorting.md'
      - "分组": 'controls/datagrid/grouping.md'
      - "筛选和搜索": 'controls/datagrid/filter-and-search.md'
      - "焦点和导航": 'controls/datagrid/focus-and-navigation.md'
      - "行拖放": 'controls/datagrid/row-drag-and-drop.md'
      - "上下文菜单": 'controls/datagrid/context-menus.md'
      - "导出": 'controls/datagrid/export.md'
      - "剪贴板": 'controls/datagrid/clipboard.md'
      - "保存和恢复布局": 'controls/datagrid/save-and-restore-layout.md'
      - "Styles": 'controls/datagrid/styles.md'
      - "性能和数据虚拟化": 'controls/datagrid/performance-and-data-virtualization.md'
      - "示例":
        - "示例": 'controls/datagrid/examples/index.md'
        - "如何为只读弹出式编辑器阻止打开弹出窗口": 'controls/datagrid/examples/how-to-prevent-opening-popups-for-read-only-popup-editors.md'
    - "TreeList 和 TreeView":
      - "TreeList 和 TreeView": 'controls/treelist/index.md'
      - "TreeList 和 TreeView 控制概述": 'controls/treelist/treelist-and-treeview-overview.md'
      - "数据绑定":
        - "数据绑定": 'controls/treelist/data-binding/index.md'
        - "绑定到层级数据": 'controls/treelist/data-binding/binding-to-hierarchical-data.md'
        - "绑定到 Self-Referential 数据源": 'controls/treelist/data-binding/binding-to-self-referential-data-source.md'
        - "未绑定模式": 'controls/treelist/data-binding/unbound-mode.md'
        - "未绑定的列": 'controls/treelist/data-binding/unbound-columns.md'
      - "Columns": 'controls/treelist/columns.md'
      - "Bands": 'controls/treelist/bands.md'
      - "节点": 'controls/treelist/nodes.md'
      - "数据编辑":
        - "数据编辑": 'controls/treelist/data-editing/index.md'
        - "TreeList 和 TreeView 单元中的自定义编辑器": 'controls/treelist/data-editing/custom-editors.md'
      - "排序": 'controls/treelist/sorting.md'
      - "过滤和搜索": 'controls/treelist/filter-and-search.md'
      - "焦点和导航": 'controls/treelist/focus-and-navigation.md'
      - "数据验证": 'controls/treelist/data-validation.md'
      - "节点拖放（Drag-and-Drop）": 'controls/treelist/node-drag-and-drop.md'
      - "上下文菜单": 'controls/treelist/context-menus.md'
      - "导出": 'controls/treelist/export.md'
      - "保存和恢复布局": 'controls/treelist/save-and-restore-layout.md'
      - "Styles": 'controls/treelist/styles.md'
      - "性能和数据虚拟化": 'controls/treelist/performance-and-data-virtualization.md'
      - "示例":
        - "示例": 'controls/treelist/examples/index.md'
        - "如何创建 TreeList 并将其绑定到层次化数据源": 'controls/treelist/examples/how-to-create-a-treelist-control-and-bind-it-to-a-hierarchical-data-source.md'
        - "如何创建 TreeView 并将其绑定到 Self-Referential 数据源": 'controls/treelist/examples/how-to-create-a-treeview-control-and-bind-it-to-a-self-referential-data-source.md'
    - "Charts":
      - "Charts": 'controls/charts/index.md'
      - "开始使用图表": 'controls/charts/get-started-with-charts.md'
      - "图表入门 - MVVM 模式": 'controls/charts/get-started-with-charts-mvvm.md'
      - "Cartesian Chart": 'controls/charts/cartesian-chart.md'
      - "笛卡尔级数视图":
        - "笛卡尔级数视图": 'controls/charts/cartesian-series-views/index.md'
        - "Line Series View": 'controls/charts/cartesian-series-views/line-series-vew.md'
        - "散点线系列视图": 'controls/charts/cartesian-series-views/scatter-line-series-view.md'
        - "Point Series View": 'controls/charts/cartesian-series-views/point-series-view.md'
        - "Area Series View": 'controls/charts/cartesian-series-views/area-series-view.md'
        - "Range Area Series View": 'controls/charts/cartesian-series-views/range-area-series-view.md'
        - "Stacked Area Series View": 'controls/charts/cartesian-series-views/stacked-area-series-view.md'
        - "Full-Stacked Area Series View": 'controls/charts/cartesian-series-views/full-stacked-area-series-view.md'
        - "Side-by-side Bar Series View": 'controls/charts/cartesian-series-views/side-by-side-bar-series-view.md'
        - "并排范围栏系列视图": 'controls/charts/cartesian-series-views/side-by-side-range-bar-series-view.md'
        - "阶梯线系列视图": 'controls/charts/cartesian-series-views/step-line-series-view.md'
        - "台阶区域系列视图": 'controls/charts/cartesian-series-views/step-area-series-view.md'
        - "Candlestick Series View": 'controls/charts/cartesian-series-views/candlestick-series-view.md'
        - "棒棒糖系列视图": 'controls/charts/cartesian-series-views/lollipop-series-view.md'
      - "十字线": 'controls/charts/crosshair.md'
      - "滚动和缩放图表控件": 'controls/charts/scroll-and-zoom-in-a-chart-control.md'
      - "热图": 'controls/charts/heatmap.md'
    - "Docking 界面":
      - "Docking 界面": 'controls/docking/index.md'
      - "Docking 入门指南": 'controls/docking/get-started-with-docking.md'
      - "Dock 管理器和 Dock 项目": 'controls/docking/dock-manager.md'
      - "停靠面板和容器": 'controls/docking/dock-panes-and-containers.md'
      - "文档面板": 'controls/docking/document-panes.md'
      - "文档切换器": 'controls/docking/document-switcher.md'
      - "在代码中执行停靠操作": 'controls/docking/perform-dock-operations-in-code.md'
      - "使用 MVVM 模式填充停靠项": 'controls/docking/use-mvvm-pattern-to-populate-dock-items.md'
      - "保存和恢复面板布局": 'controls/docking/save-and-restore-layout.md'
      - "示例":
        - "示例": 'controls/docking/examples/index.md'
        - "如何在代码后台创建复杂的 Docking 布局": 'controls/docking/examples/how-to-create-a-complex-docking-layout-in-code-behind.md'
    - "Ribbon":
      - "Ribbon": 'controls/ribbon/index.md'
      - "Ribbon 概述": 'controls/ribbon/ribbon-overview.md'
      - "页数": 'controls/ribbon/pages.md'
      - "页面分组": 'controls/ribbon/page-groups.md'
      - "Ribbon 项目": 'controls/ribbon/ribbon-items.md'
      - "Galleries": 'controls/ribbon/galleries.md'
      - "Application Button 和主菜单": 'controls/ribbon/application-button-and-main-menu.md'
      - "快速访问工具栏": 'controls/ribbon/quick-access-toolbar.md'
      - "页眉项目": 'controls/ribbon/page-header-items.md'
      - "Key Tips": 'controls/ribbon/key-tips.md'
      - "Ribbon 命令布局": 'controls/ribbon/ribbon-command-layouts.md'
      - "Ribbon 序列化和反序列化": 'controls/ribbon/ribbon-serialization-and-deserialization.md'
    - "工具栏和菜单":
      - "工具栏和菜单": 'controls/toolbars-and-menus/index.md'
      - "工具栏入门": 'controls/toolbars-and-menus/get-started-with-toolbars.md'
      - "工具栏": 'controls/toolbars-and-menus/toolbars.md'
      - "工具栏项": 'controls/toolbars-and-menus/toolbar-items.md'
      - "弹出菜单和上下文菜单": 'controls/toolbars-and-menus/popup-and-context-menus.md'
      - "工具栏序列化和反序列化": 'controls/toolbars-and-menus/toolbar-serialization-and-deserialization.md'
    - "ListView":
      - "ListView": 'controls/listview/index.md'
      - "ListView 控件入门": 'controls/listview/get-started-with-listview.md'
      - "ListView控制概述": 'controls/listview/listview-overview.md'
    - "PropertyGrid":
      - "PropertyGrid": 'controls/propertygrid/index.md'
      - "PropertyGrid 概述": 'controls/propertygrid/propertygrid-overview.md'
      - "数据绑定与行创建": 'controls/propertygrid/data-binding.md'
      - "PropertyGrid 行": 'controls/propertygrid/rows.md'
      - "数据检索": 'controls/propertygrid/data-search.md'
      - "数据编辑": 'controls/propertygrid/data-editing.md'
      - "自定义编辑器": 'controls/propertygrid/custom-editors.md'
      - "常用 API": 'controls/propertygrid/frequently-used-api.md'
    - "Graphics 3D Control":
      - "Graphics 3D Control": 'controls/graphics3dcontrol/index.md'
      - "Graphics3DControl 入门": 'controls/graphics3dcontrol/get-started-with-graphics3dcontrol.md'
      - "Graphics3DControl 概述": 'controls/graphics3dcontrol/graphics3dcontrol-overview.md'
      - "Camera": 'controls/graphics3dcontrol/camera.md'
      - "光": 'controls/graphics3dcontrol/light.md'
      - "天空盒": 'controls/graphics3dcontrol/skybox.md'
      - "导出": 'controls/graphics3dcontrol/export.md'
      - "用户与 3D 模型的交互": 'controls/graphics3dcontrol/user-interactions-with-3d-models.md'
      - "系统要求": 'controls/graphics3dcontrol/system-requirements.md'
    - "Editors":
      - "Editors": 'controls/editors/index.md'
      - "TextEditor": 'controls/editors/texteditor.md'
      - "ButtonEditor": 'controls/editors/buttoneditor.md'
      - "CheckEditor": 'controls/editors/checkeditor.md'
      - "ComboBoxEditor": 'controls/editors/comboboxeditor.md'
      - "DateEditor": 'controls/editors/dateeditor.md'
      - "HyperlinkEditor": 'controls/editors/hyperlinkeditor.md'
      - "MemoEditor": 'controls/editors/memoeditor.md'
      - "PopupColorEditor": 'controls/editors/popupcoloreditor.md'
      - "SegmentedEditor": 'controls/editors/segmentededitor.md'
      - "SpinEditor": 'controls/editors/spineditor.md'
      - "Masks":
        - "Masks": 'controls/editors/masks/index.md'
        - "数字掩码": 'controls/editors/masks/numeric-masks.md'
        - "日期时间掩码": 'controls/editors/masks/date-time-masks.md'
      - "数据验证": 'controls/editors/data-validation.md'
      - "自定义编辑器": 'controls/editors/custom-editors.md'
      - "示例":
        - "示例": 'controls/editors/examples/index.md'
        - "如何创建密码文本框": 'controls/editors/examples/How-to-create-a-password-text-box.md'
    - "实用控制":
      - "实用控制": 'controls/utility-controls/index.md'
      - "CalendarControl": 'controls/utility-controls/calendarcontrol.md'
      - "GroupBox": 'controls/utility-controls/groupbox.md'
      - "SplitButton": 'controls/utility-controls/splitbutton.md'
      - "SplitContainerControl": 'controls/utility-controls/splitcontainercontrol.md'
      - "TabControl": 'controls/utility-controls/tabcontrol.md'
    - "窗口和对话框":
      - "窗口和对话框": 'controls/windows-and-dialogs/index.md'
      - "MxWindow": 'controls/windows-and-dialogs/mxwindow.md'
      - "MxMessageBox": 'controls/windows-and-dialogs/messagebox.md'
    - "视觉主题":
      - "视觉主题": 'controls/themes/index.md'
      - "注册 Eremex 视觉主题": 'controls/themes/register-an-eremex-paint-theme.md'
      - "修改控件主题": 'controls/themes/modify-control-themes.md'
    - "故障排除":
      - "故障排除": 'controls/troubleshooting/index.md'
      - "在 Astra Linux 操作系统中窗口和菜单的阴影显示不正确": 'controls/troubleshooting/shadows-are-not-displayed-correctly-for-windows-and-menus-in-os-astra.md'
  - "包含内容":
    - "包含内容": 'whats-included/index.md'
    - "程序集": 'whats-included/assemblies.md'
    - "项目模板": 'whats-included/project-templates.md'
    - "系统要求": 'whats-included/system-requirements.md'
    - "构建期遥测": 'whats-included/build-time-telemetry.md'
    - "技术支持服务": 'whats-included/technical-support-services.md'
  - "版本历史":
    - "版本历史": 'version-history/index.md'
    - "1.4版本": 'version-history/version-1.4.md'
    - "版本 1.3": 'version-history/version-1.3.md'
    - "版本 1.2": 'version-history/version-1.2.md'
    - "版本 1.1": 'version-history/version-1.1.md'
    - "版本 1.0": 'version-history/version-1.0.md'
  - "许可":
    - "许可": 'licensing/index.md'
    - "END-USER LICENSE AGREEMENT": 'licensing/eula.md'
