INHERIT: ./base-mkdocs.yml
nav:
  - "Библиотека Eremex Avalonia UI Controls": 'index.md'
  - "Лицензирование":
    - "Лицензирование": 'licensing/index.md'
    - "ЛИЦЕНЗИОННОЕ СОГЛАШЕНИЕ С КОНЕЧНЫМ ПОЛЬЗОВАТЕЛЕМ": 'licensing/eula.md'
  - "Начало работы":
    - "Начало работы": 'get-started/index.md'
    - "Начало работы с EMX Controls": 'get-started/get-started-with-emx-controls.md'
    - "Используйте стандартные шаблоны Avalonia UI для создания нового проекта с Eremex Controls": 'get-started/create-new-avalonia-project-using-avalonia-templates.md'
    - "Начало работы с EMX Controls в ALT Linux": 'get-started/get-started-with-emx-controls-on-alt-linux.md'
  - "Контролы":
    - "Контролы": 'controls/index.md'
    - "DataGrid":
      - "DataGrid": 'controls/datagrid/index.md'
      - "Привязка данных":
        - "Привязка данных": 'controls/datagrid/data-binding/index.md'
        - "Несвязанные колонки": 'controls/datagrid/data-binding/unbound-columns.md'
      - "Columns": 'controls/datagrid/columns.md'
      - "Rows": 'controls/datagrid/rows.md'
      - "Cells": 'controls/datagrid/cells.md'
      - "Группы": 'controls/datagrid/bands.md'
      - "Редактирование данных":
        - "Редактирование данных": 'controls/datagrid/data-editing/index.md'
        - "Пользовательские редакторы": 'controls/datagrid/data-editing/custom-editors.md'
      - "Сортировка": 'controls/datagrid/sorting.md'
      - "Grouping": 'controls/datagrid/grouping.md'
      - "Фильтрация и поиск": 'controls/datagrid/filter-and-search.md'
      - "Фокус и навигация": 'controls/datagrid/focus-and-navigation.md'
      - "Перетаскивание строк (Drag-and-Drop)": 'controls/datagrid/row-drag-and-drop.md'
      - "Контекстные меню": 'controls/datagrid/context-menus.md'
      - "Экспорт": 'controls/datagrid/export.md'
      - "Clipboard": 'controls/datagrid/clipboard.md'
      - "Сохранение и восстановление лайаута": 'controls/datagrid/save-and-restore-layout.md'
      - "Styles": 'controls/datagrid/styles.md'
      - "Производительность и виртуализация данных": 'controls/datagrid/performance-and-data-virtualization.md'
      - "Примеры":
        - "Примеры": 'controls/datagrid/examples/index.md'
        - "Как предотвратить открытие всплывающих окон для редакторов только для чтения": 'controls/datagrid/examples/how-to-prevent-opening-popups-for-read-only-popup-editors.md'
    - "TreeList и TreeView":
      - "TreeList и TreeView": 'controls/treelist/index.md'
      - "Обзор контролов TreeList и TreeView": 'controls/treelist/treelist-and-treeview-overview.md'
      - "Привязка данных":
        - "Привязка данных": 'controls/treelist/data-binding/index.md'
        - "Привязка к иерархическим данным": 'controls/treelist/data-binding/binding-to-hierarchical-data.md'
        - "Привязка к Self-Referential источнику данных": 'controls/treelist/data-binding/binding-to-self-referential-data-source.md'
        - "Несвязанный режим": 'controls/treelist/data-binding/unbound-mode.md'
        - "Несвязанные колонки (TreeList)": 'controls/treelist/data-binding/unbound-columns.md'
      - "Columns": 'controls/treelist/columns.md'
      - "Группы": 'controls/treelist/bands.md'
      - "Узлы": 'controls/treelist/nodes.md'
      - "Редактирование данных":
        - "Редактирование данных": 'controls/treelist/data-editing/index.md'
        - "Пользовательские редакторы в ячейках TreeList и TreeView": 'controls/treelist/data-editing/custom-editors.md'
      - "Сортировка": 'controls/treelist/sorting.md'
      - "Фильтрация и поиск": 'controls/treelist/filter-and-search.md'
      - "Фокус и навигация": 'controls/treelist/focus-and-navigation.md'
      - "Валидация данных": 'controls/treelist/data-validation.md'
      - "Перетаскивание узлов (Drag-and-Drop)": 'controls/treelist/node-drag-and-drop.md'
      - "Контекстные меню": 'controls/treelist/context-menus.md'
      - "Экспорт": 'controls/treelist/export.md'
      - "Сохранение и восстановление лайаута": 'controls/treelist/save-and-restore-layout.md'
      - "Styles": 'controls/treelist/styles.md'
      - "Производительность и виртуализация данных": 'controls/treelist/performance-and-data-virtualization.md'
      - "Примеры TreeList и TreeView":
        - "Примеры TreeList и TreeView": 'controls/treelist/examples/index.md'
        - "Как создать TreeList и привязать его к иерархическому источнику данных": 'controls/treelist/examples/how-to-create-a-treelist-control-and-bind-it-to-a-hierarchical-data-source.md'
        - "Как создать TreeView и привязать его к Self-Referential источнику данных": 'controls/treelist/examples/how-to-create-a-treeview-control-and-bind-it-to-a-self-referential-data-source.md'
    - "Charts":
      - "Charts": 'controls/charts/index.md'
      - "Начало работы с диаграммами": 'controls/charts/get-started-with-charts.md'
      - "Начало работы с диаграммами — паттерн MVVM": 'controls/charts/get-started-with-charts-mvvm.md'
      - "Cartesian Chart": 'controls/charts/cartesian-chart.md'
      - "Представления серий":
        - "Представления серий": 'controls/charts/cartesian-series-views/index.md'
        - "Line Series View": 'controls/charts/cartesian-series-views/line-series-vew.md'
        - "Scatter Line Series View": 'controls/charts/cartesian-series-views/scatter-line-series-view.md'
        - "Point Series View": 'controls/charts/cartesian-series-views/point-series-view.md'
        - "Area Series View": 'controls/charts/cartesian-series-views/area-series-view.md'
        - "Range Area Series View": 'controls/charts/cartesian-series-views/range-area-series-view.md'
        - "Stacked Area Series View": 'controls/charts/cartesian-series-views/stacked-area-series-view.md'
        - "Full-Stacked Area Series View": 'controls/charts/cartesian-series-views/full-stacked-area-series-view.md'
        - "Side-by-side Bar Series View": 'controls/charts/cartesian-series-views/side-by-side-bar-series-view.md'
        - "Side-by-side Range Bar Series View": 'controls/charts/cartesian-series-views/side-by-side-range-bar-series-view.md'
        - "Step Line Series View": 'controls/charts/cartesian-series-views/step-line-series-view.md'
        - "Step Area Series View": 'controls/charts/cartesian-series-views/step-area-series-view.md'
        - "Candlestick Series View": 'controls/charts/cartesian-series-views/candlestick-series-view.md'
        - "Lollipop Series View": 'controls/charts/cartesian-series-views/lollipop-series-view.md'
      - "Crosshair": 'controls/charts/crosshair.md'
      - "Прокрутка и масштабирование в контроле диаграммы": 'controls/charts/scroll-and-zoom-in-a-chart-control.md'
      - "Heatmap": 'controls/charts/heatmap.md'
    - "Интерфейс Докинга":
      - "Интерфейс Докинга": 'controls/docking/index.md'
      - "Начало работы с Docking": 'controls/docking/get-started-with-docking.md'
      - "Dock Manager и элементы докинга": 'controls/docking/dock-manager.md'
      - "Dock-панели и контейнеры": 'controls/docking/dock-panes-and-containers.md'
      - "Document-панели": 'controls/docking/document-panes.md'
      - "Переключатель документов": 'controls/docking/document-switcher.md'
      - "Выполнение операций закрепления в коде": 'controls/docking/perform-dock-operations-in-code.md'
      - "Использование паттерна MVVM для заполнения элементами закрепления": 'controls/docking/use-mvvm-pattern-to-populate-dock-items.md'
      - "Сохранение и восстановление размещения панелей": 'controls/docking/save-and-restore-layout.md'
      - "Примеры докинга":
        - "Примеры докинга": 'controls/docking/examples/index.md'
        - "Как создать сложный макет для докинга в коде": 'controls/docking/examples/how-to-create-a-complex-docking-layout-in-code-behind.md'
    - "Ribbon":
      - "Ribbon": 'controls/ribbon/index.md'
      - "Обзор Ribbon": 'controls/ribbon/ribbon-overview.md'
      - "Pages": 'controls/ribbon/pages.md'
      - "Группы страниц": 'controls/ribbon/page-groups.md'
      - "Элементы Ribbon": 'controls/ribbon/ribbon-items.md'
      - "Galleries": 'controls/ribbon/galleries.md'
      - "Application Button и главное меню": 'controls/ribbon/application-button-and-main-menu.md'
      - "Панель быстрого доступа": 'controls/ribbon/quick-access-toolbar.md'
      - "Элементы заголовка страницы": 'controls/ribbon/page-header-items.md'
      - "Key Tips": 'controls/ribbon/key-tips.md'
      - "Размещение команд Ribbon": 'controls/ribbon/ribbon-command-layouts.md'
      - "Сериализация и десериализация Ribbon": 'controls/ribbon/ribbon-serialization-and-deserialization.md'
    - "Панели инструментов и меню":
      - "Панели инструментов и меню": 'controls/toolbars-and-menus/index.md'
      - "Начало работы с панелями инструментов": 'controls/toolbars-and-menus/get-started-with-toolbars.md'
      - "Toolbars": 'controls/toolbars-and-menus/toolbars.md'
      - "Элементы панели инструментов": 'controls/toolbars-and-menus/toolbar-items.md'
      - "Всплывающие и контекстные меню": 'controls/toolbars-and-menus/popup-and-context-menus.md'
      - "Сериализация и десериализация панелей инструментов": 'controls/toolbars-and-menus/toolbar-serialization-and-deserialization.md'
    - "ListView":
      - "ListView": 'controls/listview/index.md'
      - "Начало работы с контролом ListView": 'controls/listview/get-started-with-listview.md'
      - "Обзор контрола ListView": 'controls/listview/listview-overview.md'
    - "PropertyGrid":
      - "PropertyGrid": 'controls/propertygrid/index.md'
      - "Обзор контрола PropertyGrid": 'controls/propertygrid/propertygrid-overview.md'
      - "Привязка данных и создание строк": 'controls/propertygrid/data-binding.md'
      - "Строки в контроле PropertyGrid": 'controls/propertygrid/rows.md'
      - "Поиск данных": 'controls/propertygrid/data-search.md'
      - "Редактирование данных": 'controls/propertygrid/data-editing.md'
      - "Пользовательские редакторы": 'controls/propertygrid/custom-editors.md'
      - "Часто используемый API": 'controls/propertygrid/frequently-used-api.md'
    - "Graphics 3D Control":
      - "Graphics 3D Control": 'controls/graphics3dcontrol/index.md'
      - "Начало работы с Graphics3DControl": 'controls/graphics3dcontrol/get-started-with-graphics3dcontrol.md'
      - "Обзор Graphics3DControl": 'controls/graphics3dcontrol/graphics3dcontrol-overview.md'
      - "Camera": 'controls/graphics3dcontrol/camera.md'
      - "Light": 'controls/graphics3dcontrol/light.md'
      - "Skybox": 'controls/graphics3dcontrol/skybox.md'
      - "Экспорт": 'controls/graphics3dcontrol/export.md'
      - "Взаимодействие пользователя с 3D-моделями": 'controls/graphics3dcontrol/user-interactions-with-3d-models.md'
      - "Системные требования": 'controls/graphics3dcontrol/system-requirements.md'
    - "Editors":
      - "Editors": 'controls/editors/index.md'
      - "TextEditor": 'controls/editors/texteditor.md'
      - "ButtonEditor": 'controls/editors/buttoneditor.md'
      - "CheckEditor": 'controls/editors/checkeditor.md'
      - "ComboBoxEditor": 'controls/editors/comboboxeditor.md'
      - "DateEditor": 'controls/editors/dateeditor.md'
      - "HyperlinkEditor": 'controls/editors/hyperlinkeditor.md'
      - "MemoEditor": 'controls/editors/memoeditor.md'
      - "PopupColorEditor": 'controls/editors/popupcoloreditor.md'
      - "SegmentedEditor": 'controls/editors/segmentededitor.md'
      - "SpinEditor": 'controls/editors/spineditor.md'
      - "Masks":
        - "Masks": 'controls/editors/masks/index.md'
        - "Числовые маски": 'controls/editors/masks/numeric-masks.md'
        - "Маски даты и времени": 'controls/editors/masks/date-time-masks.md'
      - "Валидация данных": 'controls/editors/data-validation.md'
      - "Пользовательские редакторы": 'controls/editors/custom-editors.md'
      - "Примеры редакторов":
        - "Примеры редакторов": 'controls/editors/examples/index.md'
        - "Как создать текстовое поле для ввода пароля": 'controls/editors/examples/How-to-create-a-password-text-box.md'
    - "Вспомогательные контролы":
      - "Вспомогательные контролы": 'controls/utility-controls/index.md'
      - "CalendarControl": 'controls/utility-controls/calendarcontrol.md'
      - "GroupBox": 'controls/utility-controls/groupbox.md'
      - "SplitButton": 'controls/utility-controls/splitbutton.md'
      - "SplitContainerControl": 'controls/utility-controls/splitcontainercontrol.md'
      - "TabControl": 'controls/utility-controls/tabcontrol.md'
    - "Окна и диалоговые окна":
      - "Окна и диалоговые окна": 'controls/windows-and-dialogs/index.md'
      - "MxWindow": 'controls/windows-and-dialogs/mxwindow.md'
      - "MxMessageBox": 'controls/windows-and-dialogs/messagebox.md'
    - "Визуальные темы":
      - "Визуальные темы": 'controls/themes/index.md'
      - "Регистрация визуальной темы Eremex": 'controls/themes/register-an-eremex-paint-theme.md'
      - "Изменение тем элементов управления": 'controls/themes/modify-control-themes.md'
    - "Устранение неполадок":
      - "Устранение неполадок": 'controls/troubleshooting/index.md'
      - "Тени некорректно отображаются для окон и меню в ОС Astra Linux": 'controls/troubleshooting/shadows-are-not-displayed-correctly-for-windows-and-menus-in-os-astra.md'
  - "Что входит в комплект":
    - "Что входит в комплект": 'whats-included/index.md'
    - "Сборки": 'whats-included/assemblies.md'
    - "Шаблоны проектов": 'whats-included/project-templates.md'
    - "Системные требования": 'whats-included/system-requirements.md'
    - "Телеметрия во время сборки": 'whats-included/build-time-telemetry.md'
    - "Услуги технической поддержки": 'whats-included/technical-support-services.md'
  - "История версий":
    - "История версий": 'version-history/index.md'
    - "Версия 1.4": 'version-history/version-1.4.md'
    - "Версия 1.3": 'version-history/version-1.3.md'
    - "Версия 1.2": 'version-history/version-1.2.md'
    - "Версия 1.1": 'version-history/version-1.1.md'
    - "Версия 1.0": 'version-history/version-1.0.md'
